version: '3'
services:
    web:
        build: .
        ports:
            - "8080:80"
            - "5000:443"
        networks:
            - overlay
            
networks:
    overlay:
              